service: charon-express

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-2

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline